name: API Tests (Newman) - Hosted API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman and wait-on
        run: |
          npm install -g newman wait-on

      - name: Wait for hosted API to be ready
        run: |
          npx wait-on https://api-with-bugs.practicesoftwaretesting.com/status

      - name: Prepare Newman reports directory
        run: mkdir -p newman

      - name: Run Postman Collection - Messages
        run: |
          newman run "${{ github.workspace }}/postman/API_Testing_Messages.json" \
            --environment "${{ github.workspace }}/postman/API_Testing_env.json" \
            --iteration-data "${{ github.workspace }}/test_data/d1.json" \
            --reporters cli \
            --insecure \
            --suppress-exit-code

      - name: Run Postman Collection - Favorites
        run: |
          newman run "${{ github.workspace }}/postman/API_Testing_Favorites.json" \
            --environment "${{ github.workspace }}/postman/API_Testing_env.json" \
            --iteration-data "${{ github.workspace }}/test_data/d2.json" \
            --reporters cli \
            --insecure \
            --suppress-exit-code

      - name: Run Postman Collection - Payment
        run: |
          newman run "${{ github.workspace }}/postman/API_Testing_Payment.json" \
            --environment "${{ github.workspace }}/postman/API_Testing_env.json" \
            --iteration-data "${{ github.workspace }}/test_data/d3.json" \
            --reporters cli \
            --insecure \
            --suppress-exit-code

      - name: Upload Newman HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-reports
          path: newman/*.html
